disabled_rules: # rule identifiers to exclude from running
  - todo
#  - colon
#  - comma
#  - control_statement
  - file_length
  - force_cast
  - force_try
  - function_body_length
#  - leading_whitespace
  - line_length
  - legacy_constructor
  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
  - type_body_length
  - type_name
  - variable_name_max_length
  - variable_name_min_length
  - variable_name
  - valid_docs
  - function_parameter_count
  - cyclomatic_complexity
excluded: # paths to ignore during linting.
  - Carthage
  - Pods
  - .git
# parameterized rules can be customized from this configuration file
line_length: 300 # default 100
type_body_length:
- 200 # warning default 200
- 650 # error   default 350
function_body_length:
- 80  # warning default 40
- 250 # error   default 100
file_length:
- 400 # warning default 400
- 1300 # error  default 1000
variable_name_min_length:
- 1 # warning   default 3
- 0 # error     default 2
